name: Build Status Badge
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate badge
        run: |
          echo "![Build status](https://localhost:8081/job/vue-project-app/lastBuild/buildStatus/icon?style=plastic)" > README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
